export const GET_COMMISION = "GET_COMMISION";
export const COMMISION_ERROR = "COMMISION_ERROR";

export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";
// request types
export const SET_REQUEST = "SET_REQUEST";
export const GET_REQUEST = "GET_REQUEST";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const CLEAR_REQUEST_ERRORS = "CLEAR_REQUEST_ERRORS";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const CLEAR_REQUEST_SUCCESS = "CLEAR_REQUEST_SUCCESS";
export const SET_REQUEST_LOADING = "SET_REQUEST_LOADING";
export const CLEAR_REQUEST_LOADING = "CLEAR_REQUEST_LOADING";
export const GET_CATEGORY = "GET_CATEGORY";

//user
export const GET_USERS = "GET_USERS";
export const DELETE_USER = "DELETE_USER";
export const CLEAR_USERS = "CLEAR_USERS";
export const GET_USER_ROLE = "GET_USER_ROLE";
// export const UPDATE_USER = "UPDATE_USER";
export const USER_ERROR = "USER_ERROR";
export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";
export const USER_SUCCESS = "USER_SUCCESS";
export const CLEAR_USER_SUCCESS = "CLEAR_USER_SUCCESS";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const CLEAR_USER_LOADING = "CLEAR_USER_LOADING";

//auth

export const CLEAR_AUTH = "CLEAR_AUTH";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const CLEAR_AUTH_SUCCESS = "CLEAR_AUTH_SUCCESS";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const CLEAR_AUTH_LOADING = "CLEAR_AUTH_LOADING";
export const SET_CURRENT_ACCESS = "SET_CURRENT_ACCESS";
export const CLEAR_CURRENT_ACCESS = "CLEAR_CURRENT_ACCESS";
export const SET_ISAUTHENTICATED = "SET_ISAUTHENTICATED";
export const CLEAR_ISAUTHENTICATED = "CLEAR_ISAUTHENTICATED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";

//agent Registration

export const AGENTREG_ERROR = "AGENTREG_ERROR";
export const CLEAR_AGENTREG_ERRORS = "CLEAR_AGENTREG_ERRORS";
export const AGENTREG_SUCCESS = "AGENTREG_SUCCESS";
export const CLEAR_AGENTREG_SUCCESS = "CLEAR_AGENTREG_SUCCESS";
export const SET_AGENTREG_LOADING = "SET_AGENTREG_LOADING";
export const CLEAR_AGENTREG_LOADING = "CLEAR_AGENTREG_LOADING";
export const GET_AGENTREGINFO = " GET_AGENTREGINFO";
export const CLEAR_AGENTREGINFO = "CLEAR_AGENTREGINFO";
export const FETCH_REGISTRATIONS = "FETCH_REGISTRATIONS";

